// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#pragma once

#if defined __APPLE__

#ifdef SQL_IDENTIFIER_CASE
constexpr int SQL_IDENTIFIER_CASE_ODBC = SQL_IDENTIFIER_CASE;
#undef SQL_IDENTIFIER_CASE
#endif

#ifdef SQL_IDENTIFIER_QUOTE_CHAR
constexpr int SQL_IDENTIFIER_QUOTE_CHAR_ODBC = SQL_IDENTIFIER_QUOTE_CHAR;
#undef SQL_IDENTIFIER_QUOTE_CHAR
#endif

#ifdef SQL_QUOTED_IDENTIFIER_CASE
constexpr int SQL_QUOTED_IDENTIFIER_CASE_ODBC = SQL_QUOTED_IDENTIFIER_CASE;
#undef SQL_QUOTED_IDENTIFIER_CASE
#endif

#ifdef SQL_KEYWORDS
constexpr int SQL_KEYWORDS_ODBC = SQL_KEYWORDS;
#undef SQL_KEYWORDS
#endif

#ifdef SQL_NUMERIC_FUNCTIONS
constexpr int SQL_NUMERIC_FUNCTIONS_ODBC = SQL_NUMERIC_FUNCTIONS;
#undef SQL_NUMERIC_FUNCTIONS
#endif

#ifdef SQL_STRING_FUNCTIONS
constexpr int SQL_STRING_FUNCTIONS_ODBC = SQL_STRING_FUNCTIONS;
#undef SQL_STRING_FUNCTIONS
#endif

#ifdef SQL_SYSTEM_FUNCTIONS
constexpr int SQL_SYSTEM_FUNCTIONS_ODBC = SQL_SYSTEM_FUNCTIONS;
#undef SQL_SYSTEM_FUNCTIONS
#endif

#ifdef SQL_SCHEMA_TERM
constexpr int SQL_SCHEMA_TERM_ODBC = SQL_SCHEMA_TERM;
#undef SQL_SCHEMA_TERM
#endif

#ifdef SQL_OWNER_TERM
constexpr int SQL_OWNER_TERM_ODBC = SQL_OWNER_TERM;
#undef SQL_OWNER_TERM
#endif

#ifdef SQL_PROCEDURE_TERM
constexpr int SQL_PROCEDURE_TERM_ODBC = SQL_PROCEDURE_TERM;
#undef SQL_PROCEDURE_TERM
#endif

#ifdef SQL_CATALOG_TERM
constexpr int SQL_CATALOG_TERM_ODBC = SQL_CATALOG_TERM;
#undef SQL_CATALOG_TERM
#endif

#ifdef SQL_MAX_COLUMNS_IN_GROUP_BY
constexpr int SQL_MAX_COLUMNS_IN_GROUP_BY_ODBC = SQL_MAX_COLUMNS_IN_GROUP_BY;
#undef SQL_MAX_COLUMNS_IN_GROUP_BY
#endif

#ifdef SQL_MAX_COLUMNS_IN_INDEX
constexpr int SQL_MAX_COLUMNS_IN_INDEX_ODBC = SQL_MAX_COLUMNS_IN_INDEX;
#undef SQL_MAX_COLUMNS_IN_INDEX
#endif

#ifdef SQL_MAX_COLUMNS_IN_ORDER_BY
constexpr int SQL_MAX_COLUMNS_IN_ORDER_BY_ODBC = SQL_MAX_COLUMNS_IN_ORDER_BY;
#undef SQL_MAX_COLUMNS_IN_ORDER_BY
#endif

#ifdef SQL_MAX_COLUMNS_IN_SELECT
constexpr int SQL_MAX_COLUMNS_IN_SELECT_ODBC = SQL_MAX_COLUMNS_IN_SELECT;
#undef SQL_MAX_COLUMNS_IN_SELECT
#endif

#ifdef SQL_MAX_COLUMNS_IN_TABLE
constexpr int SQL_MAX_COLUMNS_IN_TABLE_ODBC = SQL_MAX_COLUMNS_IN_TABLE;
#undef SQL_MAX_COLUMNS_IN_TABLE
#endif

#ifdef SQL_MAX_ROW_SIZE
constexpr int SQL_MAX_ROW_SIZE_ODBC = SQL_MAX_ROW_SIZE;
#undef SQL_MAX_ROW_SIZE
#endif

#ifdef SQL_MAX_TABLES_IN_SELECT
constexpr int SQL_MAX_TABLES_IN_SELECT_ODBC = SQL_MAX_TABLES_IN_SELECT;
#undef SQL_MAX_TABLES_IN_SELECT
#endif

#ifdef SQL_CONVERT_BIGINT
constexpr int SQL_CONVERT_BIGINT_ODBC = SQL_CONVERT_BIGINT;
#undef SQL_CONVERT_BIGINT
#endif

#ifdef SQL_CONVERT_BINARY
constexpr int SQL_CONVERT_BINARY_ODBC = SQL_CONVERT_BINARY;
#undef SQL_CONVERT_BINARY
#endif

#ifdef SQL_CONVERT_BIT
constexpr int SQL_CONVERT_BIT_ODBC = SQL_CONVERT_BIT;
#undef SQL_CONVERT_BIT
#endif

#ifdef SQL_CONVERT_CHAR
constexpr int SQL_CONVERT_CHAR_ODBC = SQL_CONVERT_CHAR;
#undef SQL_CONVERT_CHAR
#endif

#ifdef SQL_CONVERT_DATE
constexpr int SQL_CONVERT_DATE_ODBC = SQL_CONVERT_DATE;
#undef SQL_CONVERT_DATE
#endif

#ifdef SQL_CONVERT_DECIMAL
constexpr int SQL_CONVERT_DECIMAL_ODBC = SQL_CONVERT_DECIMAL;
#undef SQL_CONVERT_DECIMAL
#endif

#ifdef SQL_CONVERT_FLOAT
constexpr int SQL_CONVERT_FLOAT_ODBC = SQL_CONVERT_FLOAT;
#undef SQL_CONVERT_FLOAT
#endif

#ifdef SQL_CONVERT_INTEGER
constexpr int SQL_CONVERT_INTEGER_ODBC = SQL_CONVERT_INTEGER;
#undef SQL_CONVERT_INTEGER
#endif

#ifdef SQL_CONVERT_INTERVAL_DAY_TIME
constexpr int SQL_CONVERT_INTERVAL_DAY_TIME_ODBC = SQL_CONVERT_INTERVAL_DAY_TIME;
#undef SQL_CONVERT_INTERVAL_DAY_TIME
#endif

#ifdef SQL_CONVERT_INTERVAL_YEAR_MONTH
constexpr int SQL_CONVERT_INTERVAL_YEAR_MONTH_ODBC = SQL_CONVERT_INTERVAL_YEAR_MONTH;
#undef SQL_CONVERT_INTERVAL_YEAR_MONTH
#endif

#ifdef SQL_CONVERT_LONGVARBINARY
constexpr int SQL_CONVERT_LONGVARBINARY_ODBC = SQL_CONVERT_LONGVARBINARY;
#undef SQL_CONVERT_LONGVARBINARY
#endif

#ifdef SQL_CONVERT_LONGVARCHAR
constexpr int SQL_CONVERT_LONGVARCHAR_ODBC = SQL_CONVERT_LONGVARCHAR;
#undef SQL_CONVERT_LONGVARCHAR
#endif

#ifdef SQL_CONVERT_NUMERIC
constexpr int SQL_CONVERT_NUMERIC_ODBC = SQL_CONVERT_NUMERIC;
#undef SQL_CONVERT_NUMERIC
#endif

#ifdef SQL_CONVERT_REAL
constexpr int SQL_CONVERT_REAL_ODBC = SQL_CONVERT_REAL;
#undef SQL_CONVERT_REAL
#endif

#ifdef SQL_CONVERT_SMALLINT
constexpr int SQL_CONVERT_SMALLINT_ODBC = SQL_CONVERT_SMALLINT;
#undef SQL_CONVERT_SMALLINT
#endif

#ifdef SQL_CONVERT_TIME
constexpr int SQL_CONVERT_TIME_ODBC = SQL_CONVERT_TIME;
#undef SQL_CONVERT_TIME
#endif

#ifdef SQL_CONVERT_TIMESTAMP
constexpr int SQL_CONVERT_TIMESTAMP_ODBC = SQL_CONVERT_TIMESTAMP;
#undef SQL_CONVERT_TIMESTAMP
#endif

#ifdef SQL_CONVERT_TINYINT
constexpr int SQL_CONVERT_TINYINT_ODBC = SQL_CONVERT_TINYINT;
#undef SQL_CONVERT_TINYINT
#endif

#ifdef SQL_CONVERT_VARBINARY
constexpr int SQL_CONVERT_VARBINARY_ODBC = SQL_CONVERT_VARBINARY;
#undef SQL_CONVERT_VARBINARY
#endif

#ifdef SQL_CONVERT_VARCHAR
constexpr int SQL_CONVERT_VARCHAR_ODBC = SQL_CONVERT_VARCHAR;
#undef SQL_CONVERT_VARCHAR
#endif

#ifdef BOOL
#undef BOOL
#endif

#ifdef TRUE
#undef TRUE
#endif

#ifdef FALSE
#undef FALSE
#endif

#endif  // defined __APPLE__
